title: Tech & SaaS Stack
tagline: Honest reviews, comparisons, and tutorials
description: In-depth, data-driven reviews of web hosting, SaaS tools, and software for developers, creators, and online businesses.
url: "https://fellowizsick.github.io"
baseurl: "/tech-saas-stack"
author: Jonathan Brown

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jonathan Brown"
      toc: true

future: true
permalink: /:year/:month/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
